<!-- footer -->
	
	<!-- !!!ANALYTICS!!! -->
</body>
</html>
<?php
// Database main function (does all the talking to the database class and handling of errors)
// This can be updated so that it don't let empty results through, just uncomment all comments =)
// ****************************************************************************	

	function db_MAIN($sql)
	{
		global $mysqli;
		$result = $mysqli->query( $sql );
		if ( $result )
		{

			// TODO:
			// Should fit it to work with this (maybe split this func up):
			// The mysqli_insert_id() function returns the ID generated by a query on a table with a column having the AUTO_INCREMENT attribute. If the last query wasn't an INSERT or UPDATE statement or if the modified table does not have a column with the AUTO_INCREMENT attribute, this function will return zero.
			// $mysqli->query($query);
			// printf ("New Record has id %d.\n", $mysqli->insert_id);

//			if ($result->num_rows > 0) {
				//echo "<strong>( Rows: " . $result->num_rows . " - Fields: " . $result->field_count . " )</strong><br />";
				return $result;
//			} else {
				//echo 'There are no results to display.';
//				return null;
//			}
		} else {
			printf("<div class='error'>There has been an error from MySQL: %s<br /><br />%s</div>", $mysqli->error, nl2br($sql));
			//return null;
			exit; // halta all kod, kritiskt fel
		}
	}



// Close database
// ****************************************************************************	

	$mysqli->close();



// END FILE
// ****************************************************************************
?>